---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: subject
  application:
    name  :  server-subject-words
words: I,You,He,She,It


---
spring:
  profiles: verb
  application:
    name  :  server-verb-words
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name  :  server-article-words
words: a,the

---
spring:
  profiles: adjective
  application:
    name  :  server-adjective-words
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name  :  server-noun-words
words: boat,book,vote,seat,backpack,partition,groundhog       
